CIV-6775 Integration with the List of Values API
hmcts/civil-sdk pull request #87
Opened 2023-02-23 10:58 UTC by maciejmodzelewski

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-6775

### Change description ###
Proof of Concept: Integration with the List of Values API provided by Ref Data in order to obtain civils specific data for hearing requests.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-02-23 15:24 UTC, sankaviv1 requested changes

2023-02-23 15:24 UTC, sankaviv1 commented on compose/xui.yml
> +    image: "hmctspublic.azurecr.io/xui/webapp:pr-2583"
is this intentional?

2023-02-23 15:28 UTC, maciejmodzelewski commented on compose/xui.yml
> +    image: "hmctspublic.azurecr.io/xui/webapp:pr-2583"
Not really. I can't recall actually changing this. I know, I added the 5 entries to the environment pointing at http://wiremock:8080, but not this image change. I'm baffled how this was changed.

2023-02-23 15:30 UTC, maciejmodzelewski commented on compose/xui.yml
> +    image: "hmctspublic.azurecr.io/xui/webapp:pr-2583"
I've just checked in IntelliJ Annotations and it looks like I've made that change, but I honestly can't recall doing that.

2023-02-23 15:33 UTC, maciejmodzelewski commented on compose/xui.yml
> +    image: "hmctspublic.azurecr.io/xui/webapp:pr-2583"
This message in Slack seems relevant https://hmcts-reform.slack.com/archives/C02P2Q09VAS/p1672935075411469?thread_ts=1672920045.852829&cid=C02P2Q09VAS

2023-02-23 16:08 UTC, sankaviv1 submitted a review, later dismissed

2023-02-24 09:04 UTC, Gareth40343 submitted a review, later dismissed

2023-02-24 09:14 UTC, sherlynkhaw commented on mocks/wiremock/__files/crd/categories.json
> +      "child_nodes": [
these were not in the results we got in aat, don't we want to use the aat results instead?

2023-02-24 09:24 UTC, maciejmodzelewski commented on mocks/wiremock/__files/crd/categories.json
> +      "child_nodes": [
The problem is, we don't know what is actually correct. I've created this based on the ListOfValues_24.01.2023.csv and API documentation. The response from AAT has it differently. So either the documentation is wrong or AAT returns the data incomplete/wrong. But as Harry said to me, we can tidy up the data at a later stage, there isn't really anything for us to do - it would be ref data team that does this.

2023-03-07 10:48 UTC, HarryH96 approved these changes

2023-03-07 10:51 UTC, merged